@extends('layouts.applicant')
@section('title', 'Notifications')
@section('page-title', 'Notification Center')
@section('content')
<style>
.notification-page{max-width:960px;margin:1rem auto}.notification-shell{background:#fff;border:1px solid #e0e0e0;border-radius:12px;overflow:hidden;box-shadow:0 2px 6px rgba(0,0,0,.05)}
.notification-heading{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:18px;padding:24px 28px;border-bottom:1px solid #e8ece6}.notification-heading-main{display:flex;align-items:center;gap:15px}.notification-heading-icon{width:52px;height:52px;display:grid;place-items:center;border-radius:50%;color:#fff;font-size:20px;background:linear-gradient(135deg,#7fa66f,#2d5a2d);box-shadow:0 4px 10px rgba(45,90,45,.22)}
.notification-heading h4{margin:0 0 3px;color:#222;font-weight:600;font-size:1.25rem}.notification-heading p{margin:0;color:#6c757d;font-size:.88rem}.notification-mark-all{border:1px solid #3e7b27;color:#3e7b27;background:#fff;border-radius:8px;padding:8px 14px;font-weight:600;font-size:.82rem;transition:.2s}.notification-mark-all:hover{color:#fff;background:#3e7b27}
.notification-filters{display:flex;flex-wrap:wrap;gap:8px;padding:14px 28px;background:#fafbf9;border-bottom:1px solid #e8ece6}.notification-filter{color:#555;background:#fff;border:1px solid #dde3da;border-radius:20px;padding:7px 15px;text-decoration:none;font-size:.8rem;font-weight:600;transition:.2s}.notification-filter:hover,.notification-filter.active{background:#3e7b27;border-color:#3e7b27;color:#fff}
.notification-row{position:relative;display:flex;gap:16px;padding:20px 28px;border-bottom:1px solid #edf0eb;transition:.2s}.notification-row:last-child{border-bottom:0}.notification-row:hover{background:#fafcf9}.notification-row.unread{background:#f3f9f0}.notification-row.unread:before{content:'';position:absolute;inset:0 auto 0 0;width:4px;background:#3e7b27}
.notification-type-icon{width:44px;height:44px;flex:0 0 44px;border-radius:10px;display:grid;place-items:center;font-size:17px}.notification-type-icon.approved{color:#24713b;background:#e3f4e7}.notification-type-icon.attention{color:#b53a30;background:#fce9e7}.notification-type-icon.progress{color:#946d00;background:#fff4d6}.notification-type-icon.info{color:#356a92;background:#e8f2f8}
.notification-copy{flex:1;min-width:0}.notification-title-line{display:flex;justify-content:space-between;align-items:flex-start;gap:10px}.notification-title-line h6{margin:0 0 6px;color:#252b23;font-size:.96rem;font-weight:600}.notification-new{background:#3e7b27;color:#fff;border-radius:20px;padding:3px 9px;font-size:.65rem;font-weight:600}.notification-message{color:#60675d;font-size:.86rem;line-height:1.6;margin:0 0 8px}.notification-time{color:#92988f;font-size:.75rem}
.notification-actions{display:flex;gap:8px;margin-top:13px}.notification-view,.notification-delete{border-radius:7px;padding:7px 12px;font-size:.76rem;font-weight:600;text-decoration:none;transition:.2s}.notification-view{border:0;background:#3e7b27;color:#fff}.notification-view:hover{background:#245524;color:#fff}.notification-delete{border:1px solid #e1b7b3;color:#b53a30;background:#fff}.notification-delete:hover{background:#b53a30;color:#fff}.notification-empty{padding:65px 20px;text-align:center;color:#6c757d}.notification-empty-icon{width:70px;height:70px;display:grid;place-items:center;margin:0 auto 16px;border-radius:50%;background:#f1f4ef;color:#78906e;font-size:26px}.notification-pagination{padding:16px 24px;border-top:1px solid #edf0eb}
@media(max-width:576px){.notification-heading,.notification-filters,.notification-row{padding-left:18px;padding-right:18px}.notification-heading{align-items:flex-start}.notification-mark-all{width:100%}.notification-row{gap:12px}.notification-type-icon{width:38px;height:38px;flex-basis:38px}.notification-title-line{flex-direction:column}}
</style>
<div class="notification-page">
@if(session('success'))<div class="alert alert-success border-0 shadow-sm">{{ session('success') }}</div>@endif
<section class="notification-shell">
<header class="notification-heading"><div class="notification-heading-main"><div class="notification-heading-icon"><i class="fas fa-bell"></i></div><div><h4>Your Notifications</h4><p>{{ $unreadCount }} unread {{ Str::plural('notification',$unreadCount) }}</p></div></div>
@if($unreadCount)<form method="POST" action="{{ route('applicant.notifications.read-all') }}">@csrf<button class="notification-mark-all" type="submit"><i class="fas fa-check-double me-1"></i> Mark all as read</button></form>@endif</header>
<nav class="notification-filters" aria-label="Notification filters">@foreach(['all'=>'All','unread'=>'Unread','application_submitted'=>'Submitted','application_forwarded'=>'In Progress','application_returned'=>'Corrections','application_approved'=>'Approved'] as $value=>$label)<a href="{{ route('applicant.notifications.index',['filter'=>$value]) }}" class="notification-filter {{ $filter===$value?'active':'' }}">{{ $label }}</a>@endforeach</nav>
<div>@forelse($notifications as $notification)
@php $data=$notification->data;$type=$data['type']??'general';[$tone,$icon]=match($type){'application_approved'=>['approved','fa-check'],'application_returned','application_declined'=>['attention','fa-exclamation'],'application_forwarded'=>['progress','fa-arrow-right'],'application_submitted'=>['info','fa-file-circle-check'],default=>['info','fa-bell']}; @endphp
<article class="notification-row {{ $notification->read_at?'':'unread' }}"><div class="notification-type-icon {{ $tone }}"><i class="fas {{ $icon }}"></i></div><div class="notification-copy"><div class="notification-title-line"><h6>{{ $data['title']??'Notification' }}</h6>@unless($notification->read_at)<span class="notification-new">New</span>@endunless</div><p class="notification-message">{{ $data['message']??'' }}</p><span class="notification-time"><i class="far fa-clock me-1"></i>{{ $notification->created_at->diffForHumans() }}</span><div class="notification-actions">
@unless($notification->read_at)<form method="POST" action="{{ route('applicant.notifications.read',$notification->id) }}">@csrf<button class="notification-view" type="submit">View details</button></form>@elseif(!empty($data['action_url']))<a class="notification-view" href="{{ $data['action_url'] }}">View details</a>@endif
<form method="POST" action="{{ route('applicant.notifications.destroy',$notification->id) }}" onsubmit="return confirm('Delete this notification?')">@csrf @method('DELETE')<button class="notification-delete" type="submit" title="Delete"><i class="fas fa-trash"></i></button></form></div></div></article>
@empty<div class="notification-empty"><div class="notification-empty-icon"><i class="far fa-bell-slash"></i></div><h5>No notifications found</h5><p>Updates about your COC application will appear here.</p></div>@endforelse</div>
@if($notifications->hasPages())<div class="notification-pagination">{{ $notifications->links() }}</div>@endif
</section></div>
@endsection
